<?php
// Roundcube Webmail Configuration - Generated by WebStack CLI

$config['db_dsnw'] = 'mysql://roundcube:{{.DBPassword}}@{{.DBHost}}/roundcubemail';

$config['default_host'] = array(
    'localhost:143'
);

$config['smtp_server'] = 'localhost';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

$config['support_url'] = '';

$config['product_name'] = 'WebStack Mail';

$config['cipher_method'] = 'AES-256-CBC';
$config['des_key'] = '{{.DesKey}}';

$config['log_driver'] = 'syslog';

$config['temp_dir'] = '/tmp/roundcube';

$config['enable_installer'] = false;

$config['plugins'] = array(
    'archive',
    'attachment_reminder',
    'keyboard_shortcuts',
    'newmail_notifier',
    'zipdownload',
    'managesieve',
);

$config['managesieve_host'] = 'localhost:4190';
$config['managesieve_usetls'] = true;

$config['mail_domain'] = '{{.Domain}}';

$config['username_domain'] = '{{.Domain}}';

$config['create_default_folders'] = true;

$config['delete_junk'] = false;

$config['logout_purge'] = false;

$config['logout_redirect'] = '';

$config['allow_fabrica_attachments'] = false;

$config['max_attachment_size'] = 25600;
