name: webstack-cli
version: '1.0.0'
summary: Complete web stack management CLI tool
description: |
  WebStack CLI is a comprehensive tool for installing and managing 
  a complete web development stack including Nginx, Apache, PHP-FPM, 
  MySQL/MariaDB, PostgreSQL with domain and SSL management.

  Features:
  - Install Nginx (port 80) and Apache (port 8080)
  - Install MariaDB/MySQL with phpMyAdmin
  - Install PostgreSQL with phpPgAdmin  
  - Install PHP-FPM versions 5.6 to 8.4
  - Domain management with SSL support
  - Let's Encrypt SSL certificate management

grade: stable
confinement: classic

base: core22

apps:
  webstack-cli:
    command: bin/webstack
    aliases: [webstack]

parts:
  webstack:
    plugin: go
    source: .
    build-snaps: [go/1.21/stable]
    build-packages:
      - gcc
    stage-packages:
      - ca-certificates
    override-build: |
      craftctl default
      
      # Copy templates
      mkdir -p $CRAFT_PART_INSTALL/etc/webstack
      cp -r templates $CRAFT_PART_INSTALL/etc/webstack/
      
  templates:
    plugin: dump
    source: templates/
    organize:
      '*': etc/webstack/templates/